version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cumes-backend
    overwrite: true  # Sobrescreve arquivos jรก existentes

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: ec2-user
