version: 0.0
os: linux
files:
  - source: s3://cumes-backend-deployments/dist.zip
    destination: /home/ec2-user/cumes-backend

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: ec2-user
