version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cumes-brasil/backend
    overwrite: yes
permissions:
  - object: /home/ec2-user/cumes-brasil/backend
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
