version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: cumesbr
      POSTGRES_PASSWORD: jardineiros.2024
      POSTGRES_DB: cumes-brasil
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cumes-network

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cumes-api
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: cumesbr
      DB_PASSWORD: jardineiros.2024
      DB_NAME: cumes-brasil
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - cumes-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cumes-frontend
    restart: always
    ports:
      - '80:3000'
    depends_on:
      - api
    networks:
      - cumes-network

volumes:
  db-data:

networks:
  cumes-network:
    driver: bridge
