version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cumes-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cumes-network

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cumes-api
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    networks:
      - cumes-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cumes-frontend
    restart: always
    networks:
      - cumes-network

volumes:
  db-data:

networks:
  cumes-network:
    driver: bridge
