name: Backend Deploy

on:
  push:
    paths:
      - 'backend/**'
      - 'docker-compose.yml'
      - 'scripts/**'
      - 'appspec.yml'
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156041409339:role/GitHubActionsCodeDeployRole
          aws-region: us-east-1

      # 3. Setup NodeJS
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 10. Instalar dependências do Backend
      - name: Install Backend dependencies
        working-directory: ./backend
        run: npm install --no-package-lock

      # 11. Build do Backend
      - name: Build Backend project
        working-directory: ./backend
        run: npm run build
            
      - name: Run Migrations
        working-directory: ./backend
        run: npm run migration:run

      # 12. Empacota Backend
      - name: Package Backend for Deployment
        run: |
          zip -r application.zip \
            backend/ \
            backend/package*.json \
            backend/dist/ \
            docker-compose.yml \
            appspec.yml \
            scripts/

      # 13. Upload to S3 for CodeDeploy
      - name: Upload to S3 for CodeDeploy
        run: aws s3 cp application.zip s3://cumes-backend-deployment/application.zip

      # 14. Create deployment in CodeDeploy
      - name: Create deployment in CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name cumes-backend-app \
            --deployment-group-name cumes-backend-deployment-group \
            --s3-location bucket=cumes-backend-deployment,bundleType=zip,key=application.zip
