name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Necessário para OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156041409339:role/GitHubActionsCodeDeployRole
          aws-region: us-east-1

      - name: Zip files
        run: |
          zip -r backend.zip . -x '*.git*' -x '*node_modules/*' -x '*.github/*'

      - name: Upload to S3
        run: |
          aws s3 cp backend.zip s3://cumes-backend-deployment/backend.zip

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name cumes-backend-app \
            --deployment-group-name cumes-backend-deployment-group \
            --s3-location bucket=cumes-backend-deployment,bundleType=zip,key=backend.zip
