name: Backend Deploy

on:
  push:
    paths:
      - 'backend/**'
      - 'scripts/**'
      - 'appspec.yml'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156041409339:role/GitHubActionsCodeDeployRole
          aws-region: us-east-1
        
      # 3. Empacotar o backend e scripts
      - name: Package Backend for Deployment
        run: |
          zip -r application.zip \
            backend/ \
            appspec.yml \
            scripts/

      # 4. Fazer upload do pacote para o S3
      - name: Upload to S3
        run: aws s3 cp application.zip s3://cumes-backend-deployment/application.zip

      # 5. Criar o deploy no CodeDeploy
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name cumes-backend-app \
            --deployment-group-name cumes-backend-deployment-group \
            --s3-location bucket=cumes-backend-deployment,bundleType=zip,key=application.zip
