name: Build, Deploy and Migrate Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies (including devDependencies)
        run: npm install --include=dev
        working-directory: ./backend

      - name: Archive the whole backend folder
        run: zip -r backend.zip ./
        working-directory: ./backend

      - name: Upload backend to S3
        run: |
          aws s3 cp ./backend/backend.zip s3://cumes-backend-deployments/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create Deployment via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name cumes-backend-app \
            --deployment-group-name cumes-backend-group \
            --s3-location bucket=cumes-backend-deployments,bundleType=zip,key=backend.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

  migrations:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run TypeORM Migrations
        run: npm run migration:run
        working-directory: ./backend
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
