name: Build and Deploy Application

on:
  push:
    branches:
      - NEVERSAYNEVER

jobs:
  build-and-deploy:
    name: Build and Deploy Backend and Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Necessário para OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156041409339:role/GitHubActionsCodeDeployRole
          aws-region: us-east-1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Build Frontend and upload to S3
      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install --no-package-lock

      - name: Build Frontend
        working-directory: ./frontend
        env:
          VITE_APP_API_URL: "https://api.cumesbrasil.com.br/api"
          VITE_APP_SERVER_IP: "https://d1261jj6xox5lv.cloudfront.net"
          VITE_GOOGLE_CLIENT_ID: "176876358344-1ukvkcsaoafq28cib1235cksn3nv7sm2.apps.googleusercontent.com"
        run: npm run build

      - name: Upload Frontend to S3
        run: aws s3 sync frontend/dist/pwa s3://cumes-brasil-front/ --acl public-read

      # CloudFront Invalidation for Frontend
      - name: Invalidate CloudFront Cache for Frontend
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ELJ8QUTTTNKFP \
            --paths "/*"

      # Upload Assets (Images) to S3 for CloudFront
      - name: Upload Images to S3 for CloudFront
        run: aws s3 sync backend/assets s3://cumes-brasil-images/assets --debug

      # CloudFront Invalidation for Images
      - name: Invalidate CloudFront Cache for Images
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2N1FL7EYFLAP1 \
            --paths "/*"

      # Build Backend
      - name: Install Backend dependencies
        working-directory: ./backend
        run: npm install --no-package-lock

      - name: Build Backend project
        working-directory: ./backend
        run: npm run build

      # Zip Backend for Deployment
      - name: Package Backend for Deployment
        run: |
          zip -r application.zip \
            backend/ \
            backend/package*.json \
            backend/dist/ \
            docker-compose.yml \
            appspec.yml \
            scripts/

      # Upload to S3 for CodeDeploy
      - name: Upload to S3 for CodeDeploy
        run: aws s3 cp application.zip s3://cumes-backend-deployment/application.zip

      - name: Create deployment in CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name cumes-backend-app \
            --deployment-group-name cumes-backend-deployment-group \
            --s3-location bucket=cumes-backend-deployment,bundleType=zip,key=application.zip
