name: Frontend Deploy

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1. Checkout o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156041409339:role/GitHubActionsCodeDeployRole
          aws-region: us-east-1

      # 3. Setup NodeJS
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 4. Instala dependências do Frontend
      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install --no-package-lock

      # 5. Build do Frontend
      - name: Build Frontend
        working-directory: ./frontend
        env:
          VITE_APP_API_URL: "https://api.cumesbrasil.com.br/api"
          VITE_APP_SERVER_IP: "https://d1261jj6xox5lv.cloudfront.net"
          VITE_GOOGLE_CLIENT_ID: "176876358344-1ukvkcsaoafq28cib1235cksn3nv7sm2.apps.googleusercontent.com"
        run: npm run build

      # 6. Upload do build do Frontend para o S3
      - name: Upload Frontend to S3
        run: aws s3 sync frontend/dist/pwa s3://cumes-brasil-front/ --acl public-read

      # 7. Invalidação do CloudFront para o Frontend
      - name: Invalidate CloudFront Cache (Frontend)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ELJ8QUTTTNKFP \
            --paths "/*"

      # Upload Assets (Images) to S3 for CloudFront
      - name: Upload Images to S3 for CloudFront
        run: aws s3 sync backend/assets s3://cumes-brasil-images/assets --debug

      # CloudFront Invalidation for Images
      - name: Invalidate CloudFront Cache for Images
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2N1FL7EYFLAP1 \
            --paths "/*"
